# Generated by Django 2.2.7 on 2019-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='d_o_j',
        ),
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
